### ISSUE TITLE
Data acquisition issues

### ISSUE THREAD

**Issue by zilizili** [juan1t0/scofmer#1]
Hello, I have read your paper and I am very interested in it. I would like to ask if you are willing to provide trained facial data？Thank you very much. Best wishes

**Comment by juan1t0** [comment]
Hello @zilizili,
I updated the readme file to provide the dataset I used. This is shared on my personal [drive](https://drive.google.com/file/d/1JAGejLFaymrIsq44icV42IdaAdydSdk9/view?usp=sharing).
I hope it helps

**Comment by zilizili** [comment]
Thank you very much!
