### ISSUE TITLE
Asking about Emotic dataset

### ISSUE THREAD

**Issue by ratkhohieu** [juan1t0/scofmer#2]
Hello, I have several question related to your paper and Emotic dataset. 

How can you choose the right agent from the image because sometimes there are many persons in the bounding box and it will lead to a lot of heads, faces, and poses that can be detected in one box?
And there are some noise bounding box. Did you try to process that?

**Comment by juan1t0** [comment]
Hi @ratkhohieu,
I was guided by the confidence value of the postures and faces, so when more than one appears I only take the first that exceeds a certain threshold of confidence. Regarding the noise boxes, I didn't process them, I just skipped them.
I hope I've helped.
